# This is a basic workflow to help you get started with Actions

name: CI


defaults:

  run:
  
     shell: 'bash'
     working-directory: './actions'
# permissions: 
  # actions: read
  

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      - API_URL: {{ secrets.API_URL }}
      - API_TOKEN: {{ secrets.API_TOKEN }}
      - API_CONFIG: {{ secrets.API_CONFIG }}
      - KN_CONFIG: {{ secrets.KN_CONFIG }}
      - DNS: {{ secrets.DNS }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Create Port
        inputs: []
        run: 'PORT: 234'
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install Dependencies
        run: | 
          echo "install action" 
      # npm install
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
